#!/usr/bin/env python3
"""
GapLess ローカライゼーション 追加言語ジェネレーター
出力: Dartの Map<String,String> ブロック (14言語分)
"""

LANGS = {
    'zh': {
        'name': '中文（简体）', 'flag': '🇨🇳',
        'tab_map': '地图', 'tab_guide': 'AI向导', 'tab_settings': '设置',
        'status_safe': '✅ 安全', 'status_danger': '⚠️ 危险', 'status_offline': '离线',
        'dialog_safety_title': '安全确认',
        'dialog_safety_desc': '您已安全到达？\n结束导航，切换到生活支援模式。',
        'btn_yes_arrived': '是，已到达', 'btn_cancel': '取消',
        'bot_analyzing': '分析中...', 'bot_loc_error': '⚠️ 无法获取位置。',
        'bot_found': '🔍 **找到设施**',
        'bot_found_desc': '"**@name**"在**@dist**处。请前往地图上的图标。',
        'bot_prefix_normal': '请保持冷静。我们与您同在。',
        'bot_prefix_name': '请冷静，@name。我们与您同在。',
        'bot_not_found': '⚠️ **附近未找到**',
        'bot_not_found_desc': '3公里内无数据。建议前往"避难所"。',
        'bot_go_to': '前往 @name', 'bot_dest_set': '目的地：@name',
        'bot_dest_changed': '更改：@old → @new',
        'header_emergency_gear': '紧急卡/个人信息',
        'label_name': '姓名', 'label_nation': '国籍', 'label_blood': '血型',
        'label_allergies': '过敏', 'label_needs': '特殊需求',
        'label_unknown': '未知', 'label_edit': '编辑资料',
        'header_safe_banner_title': '已到达避难所',
        'header_safe_banner_desc': '您现在处于安全位置。',
        'header_survival_guide': '官方生存指南',
        'btn_show_staff': '紧急卡（出示给工作人员）',
        'waiting_destination': '等待目的地设置...',
        'nav_dist': '距离', 'nav_calib': '校准中...', 'nav_heading': '方向',
        'bot_hospital': '🏥 前往医院', 'bot_water': '💧 前往供水点',
        'bot_safe_shelter': '🟢 前往避难所', 'bot_reroute': '⚠️ 危险绕行', 'bot_sos': '⛑️ SOS',
        'settings_title': '设置', 'settings_language': '语言', 'settings_gps': 'GPS位置',
        'settings_demo': '演示设置', 'set_about': '关于',
        'region_miyagi': '🇯🇵 宫城县（日本）', 'region_satun': '🇹🇭 沙敦（泰国）',
        'lang_japanese': '日本語', 'lang_english': 'English', 'lang_thai': 'ไทย',
        'demo_hazard': '🚨 灾难模式', 'demo_hazard_desc': '演示：显示危险状态',
        'clear_cache': '清除缓存', 'app_version': '版本', 'app_credit': 'Mitou Junior项目',
        'loc_permission_denied': '位置权限被拒绝', 'loc_open_settings': '打开设置',
        'loc_acquiring': '获取位置中...', 'loc_no_destination': '请设置目的地',
        'loc_select_in_chat': '在下方聊天中选择"避难所"',
        'shelter_evacuation': '避难所', 'shelter_school': '学校', 'shelter_hospital': '医院',
        'shelter_government': '政府', 'shelter_temple': '寺庙', 'shelter_other': '其他',
        'title': 'GapLess', 'shelters': '避难所', 'distance': '距离', 'direction': '方向',
        'verified': '已验证', 'unverified': '未验证', 'type': '类型', 'navigate': '导航',
        'set_region': '地区设置', 'set_lang': '语言', 'set_demo': '演示模式',
        'btn_arrived_label': '已到达避难所', 'header_ai_guide': 'AI疏散向导',
        'hint_name': '张三',
        'allergy_eggs': '鸡蛋', 'allergy_peanuts': '花生', 'allergy_milk': '牛奶',
        'allergy_seafood': '海鲜', 'allergy_wheat': '小麦',
        'need_wheelchair': '轮椅', 'need_visual': '视力障碍', 'need_hearing': '听力障碍',
        'need_pregnancy': '怀孕', 'need_infant': '婴儿', 'need_halal': '清真',
        'chat_prompt_main': '我能帮您什么？\n请选择话题。',
        'chat_btn_more': '其他话题', 'chat_btn_back': '返回菜单',
        'guide_economy': '经济舱综合征', 'guide_infection': '感染控制',
        'guide_poisoning': '食品安全', 'guide_insulation': '保暖',
        'guide_crime': '防犯', 'guide_rhythm': '日常节律', 'guide_chronic': '慢性病',
        'guide_religion': '宗教需求', 'guide_pet': '宠物', 'guide_mental': '心理健康',
        'guide_care': '护理', 'guide_hygiene': '卫生厕所', 'guide_battery': '省电',
        'guide_female': '女性护理', 'guide_info': '信息收集', 'guide_money': '现金贵重品',
        'guide_electric': '触电注意', 'guide_disease': '洪水传染病', 'guide_animals': '有毒动物',
        'guide_water_food': '清洁水/食物', 'guide_heat': '中暑', 'guide_emergency': '紧急联系',
        'guide_drowning': '防溺水', 'guide_boat_safety': '船只安全', 'guide_fungal': '真菌感染',
        'guide_toilet_th': '卫生设施', 'guide_mental_th': '心理健康', 'guide_documents': '重要证件',
        'guide_garbage': '垃圾处理', 'guide_chronic_th': '慢性病管理', 'guide_community': '互助',
        'guide_leech': '蚂蟥/昆虫',
        'header_category_guide': '官方生存指南', 'header_category_ai': 'AI生活支援',
        'online_ai_btn': '在线AI', 'header_shelter_support': '避难所支援',
        'btn_talk_ai': '与AI支援交流', 'btn_emergency_gear': '紧急装备',
        'btn_clear': '清除', 'msg_reset_desc': '重置所有设置', 'msg_no_data': '未找到数据',
        'label_gapless_project_main': 'GapLess项目', 'label_gapless_project': 'GapLess项目',
        'label_developed_for': 'Mitou Junior开发',
        'msg_network_restored': '网络已恢复。返回地图...',
        'msg_unknown_location': '无法引导到未知位置', 'msg_no_facility_nearby': '附近没有找到设施',
        'lbl_gps_tracking': 'GPS追踪', 'status_tracking_on': '实时追踪中',
        'status_tracking_off': '开始位置追踪', 'msg_tracking_start': 'GPS追踪已开始',
        'msg_tracking_stop': 'GPS追踪已停止', 'lbl_current_location': '当前位置',
        'lbl_no_location': '无位置', 'msg_location_cleared': '位置已清除',
        'hazard_flood': '洪水警报', 'hazard_earthquake': '地震警报', 'msg_teleport': '传送至 @name',
        'marker_shelter': '避难所', 'marker_food_supply': '食物/物资',
        'marker_flood_shelter': '洪水避难所', 'marker_official_shelter': '官方避难所',
        'official_data': '官方数据', 'navigate_here': '导航至此', 'navigation_started': '导航已开始',
        'survival_guide_tooltip': '急救与生存指南', 'triage_tooltip': '伤情检查',
        'voice_guidance': '语音导航', 'voice_on': '语音开', 'voice_off': '语音关',
        'address': '地址', 'capacity': '容量', 'capacity_unit': '人',
        'flood_support': '洪水支援', 'supported': '可用', 'not_supported': '不可用',
        'shop_type': '店铺类型', 'map_launch_failed': '无法打开地图应用',
        'msg_safer_location': '⚠️ 更改为更安全位置：@name',
        'msg_route_calculated': '✅ 安全路线已计算', 'msg_hazard_detected': '⚠️ 检测到危险区域',
        'msg_avoiding_hazard': '绕过危险区域导航',
        'splash_loading': '启动中...', 'splash_loading_lang': '加载语言数据...',
        'splash_loading_map': '加载地图和避难所数据...',
        'splash_loading_hazard': '生成危险地图（2000个点）...', 'splash_ready': '准备完成',
        'offline_banner': '离线模式：使用保存的数据',
        'disaster_mode_confirm_title': '启用灾难模式？',
        'disaster_mode_confirm_body': '切换到指南针导航，开始引导到最近的避难所。',
        'disaster_mode_confirm_ok': '启用',
        'map_download_title': '下载地图数据', 'map_download_note': '仅首次启动需要。建议使用Wi-Fi。',
        'map_download_error': '下载失败', 'map_no_connection': '无网络连接。\n请开启Wi-Fi或移动数据。',
        'map_download_failed': '@filename 下载失败。\n请重试。', 'map_download_retry': '重试',
        'map_download_done': '下载完成', 'map_info_added': '信息已添加',
        'map_tap_hint': '点击地图添加危险信息', 'map_hazard_title': '添加危险信息',
        'map_hazard_hint': '此信息将通过BLE与附近iPhone共享。不收集个人数据。',
        'map_submit': '在此添加信息', 'map_submitting': '提交中...',
        'map_ble_syncing': '与@count台设备同步', 'map_ble_waiting': 'BLE待机',
        'splash_subtitle': '灾难导航', 'splash_disclaimer_title': '免责声明',
        'splash_disclaimer_jp': 'このアプリは避難を補助するものであり、安全を完全に保証するものではありません。',
        'splash_disclaimer_en': 'This app assists evacuation but does not guarantee safety.',
        'splash_warning': '紧急情况下请遵从官方疏散指示', 'splash_agree': '同意',
        'map_title': '地图', 'compass_mode_on': '指南针模式：开', 'compass_mode_off': '指南针模式：关',
        'shelter_count': '@count 个避难所', 'label_type': '类型', 'label_coordinates': '坐标',
        'label_status': '状态', 'navigation_developing': '导航功能开发中',
        'profile_saved': '已保存', 'profile_settings': '个人资料设置', 'profile_save': '保存',
        'triage_title': '伤情检查', 'triage_back': '返回', 'triage_recommendation': '推荐行动',
        'triage_go_hospital': '导航至最近医院', 'triage_go_shelter': '导航至避难所',
        'triage_restart': '重新开始', 'location_not_available': '位置不可用',
        'dir_north': '北', 'dir_northeast': '东北', 'dir_east': '东', 'dir_southeast': '东南',
        'dir_south': '南', 'dir_southwest': '西南', 'dir_west': '西', 'dir_northwest': '西北',
        'risk_radar_title': '风险雷达', 'risk_loading': '加载风险数据...',
        'risk_high': '⚠️ 高风险 - 请谨慎移动', 'risk_medium': '注意 - 检测到危险方向',
        'risk_low': '周围相对安全',
        'danger_hazard_title': '您在危险区域', 'danger_hazard_sub': '您在危险区域内。请立即移动。',
        'danger_flood_title': '洪水风险区域', 'danger_flood_sub': '洪水风险高。请撤离到高处。',
        'danger_power_title': '触电风险区域', 'danger_power_sub': '靠近电气设备。注意积水。',
        'danger_dismiss': '关闭', 'overlay_flood': '洪水', 'overlay_power': '触电',
        'nav_straight': '直行', 'nav_turn_right': '右转', 'nav_turn_left': '左转',
        'nav_u_turn': 'U型转弯', 'nav_dist_ahead': '@dist前方', 'nav_to_dest': '至目的地',
        'nav_arrived_panel': '已到达！',
        'cal_paused': '导航暂停', 'cal_sensor_warning': '检测到磁场干扰',
        'cal_instruction': '以八字形摇动设备\n校准指南针', 'cal_skip': '跳过继续',
        'cal_divergence': 'GPS与指南针相差@deg°',
        'return_mode_label': '返回模式', 'return_dist_label': '至最后已知位置',
        'return_backtrack_btn': '原路返回',
        'qr_title': '报告此位置', 'qr_no_photo': '（无照片）',
        'qr_passable': '可通行', 'qr_passable_sub': '道路畅通',
        'qr_blocked': '被阻塞', 'qr_blocked_sub': '道路被封锁',
        'qr_danger': '此处有危险', 'qr_danger_sub': '倒塌/火灾/洪水',
        'qr_reported': '"@label"已报告',
        'dr_badge': 'GPS丢失 — 估计位置（@steps步）',
        'nav_screen_title': '安全路线', 'nav_arrive_title': '已到达目的地',
        'nav_arrive_body': '您已安全到达避难所？\n确认后显示避难所仪表板。',
        'nav_still_moving': '仍在移动', 'nav_safe_confirm': '确认安全',
        'nav_profile_title': '移动配置', 'nav_profile_standard': '标准',
        'nav_profile_standard_sub': '正常步行 (1.2 m/s)', 'nav_profile_elderly': '老年人模式',
        'nav_profile_elderly_sub': '慢速步行 (0.9 m/s)', 'nav_profile_wheelchair': '轮椅模式',
        'nav_profile_wheelchair_sub': '平坦路优先 (0.8 m/s)', 'nav_no_location': '无法获取位置',
        'nav_no_shelter': '附近没有找到避难所', 'nav_route_calculated': '到 @name 的路线已计算',
        'nav_calculating': '计算路线中...', 'nav_loading_map': '加载地图数据...',
        'nav_reported_passable': '"可通行"已报告', 'nav_reported_blocked': '"被阻塞"已报告',
        'nav_route_to': '正在计算到 @name 的路线...',
        'nav_tab_map': '导航', 'nav_tab_card': '紧急卡', 'nav_tab_guide': '指南', 'nav_tab_settings': '设置',
        'nav_tooltip_photo': '拍照快速报告', 'nav_tooltip_report': '报告道路状况',
        'nav_nearest_shelter': '最近避难所',
        'road_report_title': '报告当前位置道路状况',
        'road_report_hint': '此报告将通过蓝牙与附近用户共享。',
        'report_passable': '可通行', 'report_blocked': '被阻塞',
        'gps_none': '无GPS', 'ble_off': 'BLE关闭', 'power_saving': '省电',
        'home_no_location': '无法获取位置', 'home_danger_title': '报告危险',
        'home_report_passable': '此路可通行', 'home_report_blocked': '此路被阻塞',
        'home_report_danger': '有危险区域', 'home_report_sent': '报告已发送',
        'settings_map_updated': '地图数据已更新', 'settings_update_failed': '更新失败：@error',
        'status_safe': '✅ 安全', 'settings_gps': 'GPS位置', 'set_about': '关于',
        'region_miyagi': '🇯🇵 宫城县（日本）', 'region_satun': '🇹🇭 沙敦（泰国）',
        'demo_hazard': '🚨 灾难模式', 'demo_hazard_desc': '演示：显示危险状态',
        'clear_cache': '清除缓存', 'app_version': '版本', 'app_credit': 'Mitou Junior项目',
        'tts_narrow_road': '前方路窄@width米，请注意',
        'tts_turn': '@dist后向@direction转', 'tts_dir_right': '右', 'tts_dir_left': '左',
        'tts_arrived': '您已到达目的地。',
        'tts_waypoint': '检查点通过。剩余@dist。',
        'tts_out_of_bounds': '超出地图范围。切换到返回模式。',
        'tts_backtrack': '正在引导您原路返回。',
        'tts_distance_m': '@dist米', 'tts_distance_km': '@dist千米',
        'tts_danger_ahead': '前方有危险，请注意。',
    },
}

# zh_TW - Traditional Chinese (繁體中文)
LANGS['zh_TW'] = dict(LANGS['zh'])
LANGS['zh_TW'].update({
    'name': '中文（繁體）', 'flag': '🇹🇼',
    'tab_map': '地圖', 'tab_guide': 'AI嚮導', 'tab_settings': '設定',
    'status_safe': '✅ 安全', 'status_danger': '⚠️ 危險',
    'dialog_safety_title': '安全確認',
    'dialog_safety_desc': '您已安全到達？\n結束導航，切換到生活支援模式。',
    'btn_yes_arrived': '是，已到達',
    'bot_analyzing': '分析中...', 'bot_loc_error': '⚠️ 無法獲取位置。',
    'bot_found': '🔍 **找到設施**',
    'bot_found_desc': '"**@name**"在**@dist**處。請前往地圖上的圖示。',
    'bot_prefix_normal': '請保持冷靜。我們與您同在。',
    'bot_prefix_name': '請冷靜，@name。我們與您同在。',
    'bot_not_found': '⚠️ **附近未找到**',
    'bot_not_found_desc': '3公里內無資料。建議前往「避難所」。',
    'bot_go_to': '前往 @name', 'bot_dest_set': '目的地：@name',
    'header_emergency_gear': '緊急卡/個人資訊',
    'header_safe_banner_title': '已到達避難所',
    'header_safe_banner_desc': '您現在處於安全位置。',
    'header_survival_guide': '官方生存指南',
    'btn_show_staff': '緊急卡（出示給工作人員）',
    'waiting_destination': '等待目的地設定...',
    'settings_title': '設定', 'settings_language': '語言', 'settings_gps': 'GPS位置',
    'set_about': '關於',
    'region_miyagi': '🇯🇵 宮城縣（日本）', 'region_satun': '🇹🇭 沙敦（泰國）',
    'demo_hazard': '🚨 災難模式', 'demo_hazard_desc': '演示：顯示危險狀態',
    'clear_cache': '清除快取', 'app_version': '版本', 'app_credit': 'Mitou Junior專案',
    'loc_acquiring': '獲取位置中...', 'loc_no_destination': '請設定目的地',
    'loc_select_in_chat': '在下方聊天中選擇「避難所」',
    'title': 'GapLess', 'shelters': '避難所', 'verified': '已驗證', 'unverified': '未驗證',
    'btn_arrived_label': '已到達避難所', 'header_ai_guide': 'AI疏散嚮導',
    'hint_name': '張三',
    'allergy_eggs': '雞蛋', 'allergy_peanuts': '花生', 'allergy_milk': '牛奶',
    'allergy_seafood': '海鮮', 'allergy_wheat': '小麥',
    'need_wheelchair': '輪椅', 'need_visual': '視力障礙', 'need_hearing': '聽力障礙',
    'chat_prompt_main': '我能幫您什麼？\n請選擇話題。',
    'chat_btn_more': '其他話題', 'chat_btn_back': '返回選單',
    'status_safe': '✅ 安全', 'settings_gps': 'GPS位置', 'set_about': '關於',
    'dir_north': '北', 'dir_northeast': '東北', 'dir_east': '東', 'dir_southeast': '東南',
    'dir_south': '南', 'dir_southwest': '西南', 'dir_west': '西', 'dir_northwest': '西北',
    'nav_straight': '直行', 'nav_turn_right': '右轉', 'nav_turn_left': '左轉',
    'nav_u_turn': 'U型迴轉', 'nav_dist_ahead': '@dist前方',
    'overlay_flood': '洪水', 'overlay_power': '觸電',
    'danger_dismiss': '關閉',
    'dr_badge': 'GPS遺失 — 估計位置（@steps步）',
    'tts_dir_right': '右', 'tts_dir_left': '左',
    'tts_arrived': '您已到達目的地。',
    'tts_distance_m': '@dist公尺', 'tts_distance_km': '@dist公里',
})

# ko - Korean (한국어)
LANGS['ko'] = {
    'name': '한국어', 'flag': '🇰🇷',
    'tab_map': '지도', 'tab_guide': 'AI 가이드', 'tab_settings': '설정',
    'status_safe': '✅ 안전', 'status_danger': '⚠️ 위험', 'status_offline': '오프라인',
    'dialog_safety_title': '안전 확인',
    'dialog_safety_desc': '안전하게 도착하셨나요?\n탐색을 종료하고 지원 모드로 전환합니다.',
    'btn_yes_arrived': '예, 도착했습니다', 'btn_cancel': '취소',
    'bot_analyzing': '분석 중...', 'bot_loc_error': '⚠️ 위치를 가져올 수 없습니다.',
    'bot_found': '🔍 **시설 발견**',
    'bot_found_desc': '"**@name**"이 **@dist** 앞에 있습니다. 지도의 아이콘을 향해 이동하세요.',
    'bot_prefix_normal': '침착하세요. 우리가 함께합니다.',
    'bot_prefix_name': '침착하세요, @name. 우리가 함께합니다.',
    'bot_not_found': '⚠️ **근처 없음**',
    'bot_not_found_desc': '3km 내 데이터 없음. "대피소"로 이동을 권장합니다.',
    'bot_go_to': '@name으로 이동', 'bot_dest_set': '목적지：@name',
    'bot_dest_changed': '변경：@old → @new',
    'header_emergency_gear': '긴급 카드/프로필',
    'label_name': '이름', 'label_nation': '국적', 'label_blood': '혈액형',
    'label_allergies': '알레르기', 'label_needs': '특별 요구',
    'label_unknown': '모름', 'label_edit': '프로필 편집',
    'header_safe_banner_title': '대피소 도착',
    'header_safe_banner_desc': '안전한 곳에 있습니다.',
    'header_survival_guide': '공식 생존 가이드',
    'btn_show_staff': '긴급 카드（직원에게 보이기）',
    'waiting_destination': '목적지 설정 대기 중...',
    'nav_dist': '거리', 'nav_calib': '보정 중...', 'nav_heading': '방향',
    'bot_hospital': '🏥 병원으로', 'bot_water': '💧 급수소로',
    'bot_safe_shelter': '🟢 대피소로', 'bot_reroute': '⚠️ 위험 우회', 'bot_sos': '⛑️ SOS',
    'settings_title': '설정', 'settings_language': '언어', 'settings_gps': 'GPS 위치',
    'settings_demo': '데모 설정', 'set_about': '정보',
    'region_miyagi': '🇯🇵 미야기（일본）', 'region_satun': '🇹🇭 사툰（태국）',
    'lang_japanese': '日本語', 'lang_english': 'English', 'lang_thai': 'ไทย',
    'demo_hazard': '🚨 재난 모드', 'demo_hazard_desc': '데모：위험 상태 표시',
    'clear_cache': '캐시 삭제', 'app_version': '버전', 'app_credit': 'Mitou Junior 프로젝트',
    'loc_permission_denied': '위치 권한 거부됨', 'loc_open_settings': '설정 열기',
    'loc_acquiring': '위치 획득 중...', 'loc_no_destination': '목적지를 설정하세요',
    'loc_select_in_chat': '아래 채팅에서 "대피소" 선택',
    'title': 'GapLess', 'shelters': '대피소', 'distance': '거리', 'direction': '방향',
    'verified': '확인됨', 'unverified': '미확인', 'type': '유형', 'navigate': '탐색',
    'set_region': '지역 설정', 'set_lang': '언어', 'set_demo': '데모 모드',
    'btn_arrived_label': '대피소 도착', 'header_ai_guide': 'AI 대피 가이드',
    'hint_name': '홍길동',
    'allergy_eggs': '달걀', 'allergy_peanuts': '땅콩', 'allergy_milk': '우유',
    'allergy_seafood': '해산물', 'allergy_wheat': '밀',
    'need_wheelchair': '휠체어', 'need_visual': '시각 장애', 'need_hearing': '청각 장애',
    'need_pregnancy': '임신', 'need_infant': '영유아', 'need_halal': '할랄',
    'chat_prompt_main': '무엇을 도와드릴까요？\n주제를 선택하세요.',
    'chat_btn_more': '다른 주제', 'chat_btn_back': '메뉴로 돌아가기',
    'guide_economy': '이코노미 증후군', 'guide_infection': '감염 관리',
    'guide_poisoning': '식품 안전', 'guide_insulation': '보온', 'guide_crime': '범죄 예방',
    'guide_rhythm': '일과', 'guide_chronic': '만성 질환', 'guide_religion': '종교적 필요',
    'guide_pet': '반려동물', 'guide_mental': '정신 건강', 'guide_care': '간호',
    'guide_hygiene': '화장실·위생', 'guide_battery': '배터리 절약',
    'guide_female': '여성 케어', 'guide_info': '정보 수집', 'guide_money': '현금·귀중품',
    'guide_electric': '감전 주의', 'guide_disease': '홍수 전염병', 'guide_animals': '독성 동물',
    'guide_water_food': '식수/식품', 'guide_heat': '열사병', 'guide_emergency': '비상 연락처',
    'guide_drowning': '익수 예방', 'guide_boat_safety': '선박 안전', 'guide_fungal': '진균 감염',
    'guide_toilet_th': '위생 시설', 'guide_mental_th': '정신 건강', 'guide_documents': '중요 서류',
    'guide_garbage': '쓰레기 처리', 'guide_chronic_th': '만성 질환 관리', 'guide_community': '상호 부조',
    'guide_leech': '거머리·곤충',
    'header_category_guide': '공식 생존 가이드', 'header_category_ai': 'AI 생활 지원',
    'online_ai_btn': '온라인 AI', 'header_shelter_support': '대피소 지원',
    'btn_talk_ai': 'AI 지원과 대화', 'btn_emergency_gear': '긴급 장비',
    'btn_clear': '지우기', 'msg_reset_desc': '모든 설정 초기화', 'msg_no_data': '데이터 없음',
    'label_gapless_project_main': 'GapLess 프로젝트', 'label_gapless_project': 'GapLess 프로젝트',
    'label_developed_for': 'Mitou Junior 개발',
    'msg_network_restored': '네트워크 복구됨. 지도로 돌아갑니다...',
    'msg_unknown_location': '알 수 없는 위치로 안내 불가', 'msg_no_facility_nearby': '근처에 시설 없음',
    'lbl_gps_tracking': 'GPS 추적', 'status_tracking_on': '실시간 추적 중',
    'status_tracking_off': '위치 추적 시작', 'msg_tracking_start': 'GPS 추적 시작됨',
    'msg_tracking_stop': 'GPS 추적 중지됨', 'lbl_current_location': '현재 위치',
    'lbl_no_location': '위치 없음', 'msg_location_cleared': '위치 지워짐',
    'hazard_flood': '홍수 경보', 'hazard_earthquake': '지진 경보', 'msg_teleport': '@name으로 이동',
    'marker_shelter': '대피소', 'marker_food_supply': '식량/물자',
    'marker_flood_shelter': '홍수 대피소', 'marker_official_shelter': '공식 대피소',
    'official_data': '공식 데이터', 'navigate_here': '여기로 탐색', 'navigation_started': '탐색 시작',
    'survival_guide_tooltip': '응급처치·생존 가이드', 'triage_tooltip': '부상 확인',
    'voice_guidance': '음성 안내', 'voice_on': '음성 켜기', 'voice_off': '음성 끄기',
    'address': '주소', 'capacity': '수용 인원', 'capacity_unit': '명',
    'flood_support': '홍수 지원', 'supported': '가능', 'not_supported': '불가',
    'shop_type': '상점 유형', 'map_launch_failed': '지도 앱을 열 수 없습니다',
    'msg_safer_location': '⚠️ 더 안전한 위치로 변경：@name',
    'msg_route_calculated': '✅ 안전 경로 계산 완료', 'msg_hazard_detected': '⚠️ 위험 구역 감지',
    'msg_avoiding_hazard': '위험 구역 우회 탐색',
    'splash_loading': '시작 중...', 'splash_loading_lang': '언어 데이터 로딩 중...',
    'splash_loading_map': '지도·대피소 데이터 로딩 중...',
    'splash_loading_hazard': '위험 지도 생성 중（2000개 지점）...', 'splash_ready': '준비 완료',
    'offline_banner': '오프라인 모드：저장된 데이터 사용 중',
    'disaster_mode_confirm_title': '재난 모드 활성화？',
    'disaster_mode_confirm_body': '나침반 탐색으로 전환하여 최근 대피소로 안내 시작.',
    'disaster_mode_confirm_ok': '활성화',
    'map_download_title': '지도 데이터 다운로드', 'map_download_note': '첫 실행 시만 필요합니다. Wi-Fi 권장.',
    'map_download_error': '다운로드 실패', 'map_no_connection': '인터넷 연결 없음.\nWi-Fi 또는 모바일 데이터를 켜세요.',
    'map_download_failed': '@filename 다운로드 실패.\n다시 시도하세요.', 'map_download_retry': '재시도',
    'map_download_done': '다운로드 완료', 'map_info_added': '정보 추가됨',
    'map_tap_hint': '지도를 탭하여 위험 정보 추가', 'map_hazard_title': '위험 정보 추가',
    'map_hazard_hint': '이 정보는 BLE를 통해 근처 iPhone과 공유됩니다. 개인 정보는 수집하지 않습니다.',
    'map_submit': '여기에 정보 추가', 'map_submitting': '제출 중...',
    'map_ble_syncing': '@count대와 동기화 중', 'map_ble_waiting': 'BLE 대기 중',
    'splash_subtitle': '재난 탐색', 'splash_disclaimer_title': '면책 조항',
    'splash_disclaimer_jp': 'このアプリは避難を補助するものです。',
    'splash_disclaimer_en': 'This app assists evacuation but does not guarantee safety.',
    'splash_warning': '긴급 시 공식 대피 지시를 따르세요', 'splash_agree': '동의',
    'map_title': '지도', 'compass_mode_on': '나침반 모드：켜기', 'compass_mode_off': '나침반 모드：끄기',
    'shelter_count': '@count개 대피소', 'label_type': '유형', 'label_coordinates': '좌표',
    'label_status': '상태', 'navigation_developing': '탐색 기능 개발 중',
    'profile_saved': '저장됨', 'profile_settings': '프로필 설정', 'profile_save': '저장',
    'triage_title': '부상 확인', 'triage_back': '뒤로', 'triage_recommendation': '권장 행동',
    'triage_go_hospital': '가장 가까운 병원으로 탐색', 'triage_go_shelter': '대피소로 탐색',
    'triage_restart': '다시 시작', 'location_not_available': '위치 사용 불가',
    'dir_north': '북', 'dir_northeast': '북동', 'dir_east': '동', 'dir_southeast': '남동',
    'dir_south': '남', 'dir_southwest': '남서', 'dir_west': '서', 'dir_northwest': '북서',
    'risk_radar_title': '위험 레이더', 'risk_loading': '위험 데이터 로딩 중...',
    'risk_high': '⚠️ 고위험 - 주의해서 이동하세요', 'risk_medium': '주의 - 위험한 방향 감지됨',
    'risk_low': '주변은 비교적 안전합니다',
    'danger_hazard_title': '위험 구역 안에 있습니다', 'danger_hazard_sub': '즉시 이동하세요.',
    'danger_flood_title': '홍수 위험 구역', 'danger_flood_sub': '홍수 위험 높음. 고지대로 대피하세요.',
    'danger_power_title': '감전 위험 구역', 'danger_power_sub': '전기 설비 근처. 물웅덩이 주의.',
    'danger_dismiss': '닫기', 'overlay_flood': '홍수', 'overlay_power': '감전',
    'nav_straight': '직진', 'nav_turn_right': '우회전', 'nav_turn_left': '좌회전',
    'nav_u_turn': 'U턴', 'nav_dist_ahead': '@dist 앞', 'nav_to_dest': '목적지까지',
    'nav_arrived_panel': '도착!',
    'cal_paused': '탐색 일시중지', 'cal_sensor_warning': '자기 간섭 감지',
    'cal_instruction': '기기를 8자로 흔들어\n나침반을 보정하세요', 'cal_skip': '건너뛰고 계속',
    'cal_divergence': 'GPS와 나침반이 @deg° 차이납니다',
    'return_mode_label': '귀환 모드', 'return_dist_label': '마지막 알려진 위치까지',
    'return_backtrack_btn': '왔던 길로 되돌아가기',
    'qr_title': '이 위치 신고', 'qr_no_photo': '（사진 없음）',
    'qr_passable': '통행 가능', 'qr_passable_sub': '도로 통행 가능',
    'qr_blocked': '차단됨', 'qr_blocked_sub': '도로가 막혀 있습니다',
    'qr_danger': '여기 위험', 'qr_danger_sub': '붕괴/화재/홍수',
    'qr_reported': '"@label" 신고됨',
    'dr_badge': 'GPS 소실 — 추정 위치（@steps걸음）',
    'nav_screen_title': '안전 경로', 'nav_arrive_title': '목적지 도착',
    'nav_arrive_body': '대피소에 안전하게 도착했나요？\n확인하면 대피소 대시보드를 표시합니다.',
    'nav_still_moving': '이동 중', 'nav_safe_confirm': '안전 확인',
    'nav_profile_title': '이동 프로필', 'nav_profile_standard': '표준',
    'nav_profile_standard_sub': '보통 걷기 (1.2 m/s)', 'nav_profile_elderly': '노인 모드',
    'nav_profile_elderly_sub': '천천히 걷기 (0.9 m/s)', 'nav_profile_wheelchair': '휠체어 모드',
    'nav_profile_wheelchair_sub': '평탄 도로 우선 (0.8 m/s)', 'nav_no_location': '위치 가져오기 불가',
    'nav_no_shelter': '근처에 대피소 없음', 'nav_route_calculated': '@name으로의 경로 계산됨',
    'nav_calculating': '경로 계산 중...', 'nav_loading_map': '지도 데이터 로딩 중...',
    'nav_reported_passable': '"통행 가능" 신고됨', 'nav_reported_blocked': '"차단됨" 신고됨',
    'nav_route_to': '@name으로의 경로 계산 중...',
    'nav_tab_map': '탐색', 'nav_tab_card': '긴급 카드', 'nav_tab_guide': '가이드', 'nav_tab_settings': '설정',
    'nav_tooltip_photo': '사진으로 신속 신고', 'nav_tooltip_report': '도로 상태 신고',
    'nav_nearest_shelter': '가장 가까운 대피소',
    'road_report_title': '현재 위치 도로 상태 신고',
    'road_report_hint': '이 신고는 블루투스를 통해 근처 사용자와 공유됩니다.',
    'report_passable': '통행 가능', 'report_blocked': '차단됨',
    'gps_none': 'GPS 없음', 'ble_off': 'BLE 꺼짐', 'power_saving': '절전',
    'home_no_location': '위치 가져오기 불가', 'home_danger_title': '위험 신고',
    'home_report_passable': '이 도로 통행 가능', 'home_report_blocked': '이 도로 차단됨',
    'home_report_danger': '위험한 지역 있음', 'home_report_sent': '신고 전송됨',
    'settings_map_updated': '지도 데이터 업데이트됨', 'settings_update_failed': '업데이트 실패：@error',
    'tts_narrow_road': '전방 도로 폭 @width미터. 주의하세요.',
    'tts_turn': '@dist 후 @direction으로 회전', 'tts_dir_right': '오른쪽', 'tts_dir_left': '왼쪽',
    'tts_arrived': '목적지에 도착했습니다.',
    'tts_waypoint': '체크포인트 통과. 나머지 @dist.',
    'tts_out_of_bounds': '지도 범위 밖. 귀환 모드로 전환.',
    'tts_backtrack': '기록된 경로로 역순 안내 중.',
    'tts_distance_m': '@dist미터', 'tts_distance_km': '@dist킬로미터',
    'tts_danger_ahead': '전방 위험. 주의하세요.',
    'shelter_evacuation': '대피소', 'shelter_school': '학교', 'shelter_hospital': '병원',
    'shelter_government': '정부', 'shelter_temple': '사원', 'shelter_other': '기타',
}

def make_simple_lang(code, name, flag, translations_from_en):
    """英語から最小限の翻訳でlangを作る"""
    en = {
        'tab_map': 'Map', 'tab_guide': 'AI Guide', 'tab_settings': 'Settings',
        'status_safe': '✅ SAFE', 'status_danger': '⚠️ HAZARD',
        'btn_yes_arrived': 'Yes, Arrived', 'btn_cancel': 'Cancel',
        'bot_analyzing': 'Analyzing...', 'header_ai_guide': 'AI Guide',
        'btn_arrived_label': 'Arrived', 'waiting_destination': 'Set destination...',
        'loc_acquiring': 'Getting location...', 'loc_no_destination': 'Set destination',
        'dir_north': 'N', 'dir_northeast': 'NE', 'dir_east': 'E', 'dir_southeast': 'SE',
        'dir_south': 'S', 'dir_southwest': 'SW', 'dir_west': 'W', 'dir_northwest': 'NW',
        'nav_straight': 'Straight', 'nav_turn_right': 'Turn Right', 'nav_turn_left': 'Turn Left',
        'nav_u_turn': 'U-turn', 'nav_arrived_panel': 'Arrived!',
        'danger_dismiss': 'OK', 'overlay_flood': 'Flood', 'overlay_power': 'Electric',
        'dr_badge': 'GPS lost — Est. position (@steps steps)',
        'splash_agree': 'Agree',
        'map_download_retry': 'Retry', 'map_download_done': 'Done', 'map_submitting': 'Sending...',
        'report_passable': 'Passable', 'report_blocked': 'Blocked',
        'gps_none': 'No GPS', 'ble_off': 'BLE off', 'power_saving': 'Power save',
        'tts_dir_right': 'right', 'tts_dir_left': 'left', 'tts_arrived': 'Arrived.',
        'profile_saved': 'Saved', 'profile_save': 'Save',
        'triage_back': 'Back', 'triage_restart': 'Retry',
        'btn_clear': 'Clear', 'msg_no_data': 'No data',
        'verified': 'Verified', 'unverified': 'Unverified',
        'nav_calculating': 'Calculating...', 'nav_loading_map': 'Loading map...',
        'nav_safe_confirm': 'Confirm', 'nav_still_moving': 'Moving',
        'splash_ready': 'Ready', 'offline_banner': 'Offline mode',
    }
    d = dict(en)
    d['name'] = name
    d['flag'] = flag
    d.update(translations_from_en)
    return d

LANGS['fil'] = make_simple_lang('fil', 'Filipino', '🇵🇭', {
    'tab_map': 'Mapa', 'tab_guide': 'Gabay', 'tab_settings': 'Mga Setting',
    'status_safe': '✅ LIGTAS', 'status_danger': '⚠️ PANGANIB',
    'btn_yes_arrived': 'Oo, Nakarating', 'btn_cancel': 'Kanselahin',
    'bot_analyzing': 'Sinusuri...', 'header_ai_guide': 'Gabay sa Paglikas',
    'btn_arrived_label': 'Nakarating sa Kanlungan', 'waiting_destination': 'Magtakda ng patutunguhan...',
    'loc_acquiring': 'Kinukuha ang lokasyon...', 'loc_no_destination': 'Magtakda ng patutunguhan',
    'dir_north': 'H', 'dir_northeast': 'HS', 'dir_east': 'S', 'dir_southeast': 'TS',
    'dir_south': 'T', 'dir_southwest': 'TK', 'dir_west': 'K', 'dir_northwest': 'HK',
    'nav_straight': 'Diretso', 'nav_turn_right': 'Kanan', 'nav_turn_left': 'Kaliwa',
    'nav_u_turn': 'U-turn', 'nav_arrived_panel': 'Nakarating!',
    'danger_dismiss': 'Isara', 'overlay_flood': 'Baha', 'overlay_power': 'Kuryente',
    'dr_badge': 'Nawala GPS — Est. posisyon (@steps hakbang)',
    'splash_agree': 'Sumasang-ayon', 'report_passable': 'Madadaanan', 'report_blocked': 'Naharang',
    'gps_none': 'Walang GPS', 'ble_off': 'BLE naka-off', 'power_saving': 'Tipid ng baterya',
    'tts_dir_right': 'kanan', 'tts_dir_left': 'kaliwa', 'tts_arrived': 'Nakarating ka na.',
    'profile_save': 'I-save', 'triage_back': 'Bumalik', 'btn_clear': 'I-clear',
    'nav_calculating': 'Kinakalkula...', 'nav_safe_confirm': 'Kumpirmahin',
    'splash_ready': 'Handa na', 'offline_banner': 'Offline mode',
    'map_download_retry': 'Subukan muli', 'map_download_done': 'Tapos na',
    'msg_no_data': 'Walang data', 'verified': 'Na-verify',
})

LANGS['id'] = make_simple_lang('id', 'Bahasa Indonesia', '🇮🇩', {
    'tab_map': 'Peta', 'tab_guide': 'Panduan', 'tab_settings': 'Pengaturan',
    'status_safe': '✅ AMAN', 'status_danger': '⚠️ BAHAYA',
    'btn_yes_arrived': 'Ya, Sudah Tiba', 'btn_cancel': 'Batal',
    'bot_analyzing': 'Menganalisis...', 'header_ai_guide': 'Panduan Evakuasi AI',
    'btn_arrived_label': 'Tiba di Tempat Pengungsian', 'waiting_destination': 'Atur tujuan...',
    'loc_acquiring': 'Mendapatkan lokasi...', 'loc_no_destination': 'Atur tujuan',
    'dir_north': 'U', 'dir_northeast': 'TL', 'dir_east': 'T', 'dir_southeast': 'TG',
    'dir_south': 'S', 'dir_southwest': 'BD', 'dir_west': 'B', 'dir_northwest': 'BL',
    'nav_straight': 'Lurus', 'nav_turn_right': 'Belok Kanan', 'nav_turn_left': 'Belok Kiri',
    'nav_u_turn': 'Putar Balik', 'nav_arrived_panel': 'Tiba!',
    'danger_dismiss': 'Tutup', 'overlay_flood': 'Banjir', 'overlay_power': 'Listrik',
    'dr_badge': 'GPS hilang — Perkiraan posisi (@steps langkah)',
    'splash_agree': 'Setuju', 'report_passable': 'Bisa dilewati', 'report_blocked': 'Diblokir',
    'gps_none': 'Tidak ada GPS', 'ble_off': 'BLE mati', 'power_saving': 'Hemat daya',
    'tts_dir_right': 'kanan', 'tts_dir_left': 'kiri', 'tts_arrived': 'Anda telah tiba.',
    'profile_save': 'Simpan', 'triage_back': 'Kembali', 'btn_clear': 'Hapus',
    'nav_calculating': 'Menghitung...', 'nav_safe_confirm': 'Konfirmasi',
    'splash_ready': 'Siap', 'offline_banner': 'Mode offline',
    'map_download_retry': 'Coba lagi', 'map_download_done': 'Selesai',
    'msg_no_data': 'Tidak ada data', 'verified': 'Terverifikasi',
})

LANGS['my'] = make_simple_lang('my', 'မြန်မာ', '🇲🇲', {
    'tab_map': 'မြေပုံ', 'tab_guide': 'လမ်းညွှန်', 'tab_settings': 'ဆက်တင်',
    'status_safe': '✅ လုံခြုံ', 'status_danger': '⚠️ အန္တရာယ်',
    'btn_yes_arrived': 'ဟုတ်၊ ရောက်ပြီ', 'btn_cancel': 'မဲ့',
    'bot_analyzing': 'စစ်ဆေးနေ...', 'header_ai_guide': 'AI ဆွေးနွေးမှုလမ်းညွှန်',
    'btn_arrived_label': 'ခိုလှုံရာနေရာသို့ ရောက်ပြီ', 'waiting_destination': 'ဦးတည်ရာသတ်မှတ်ပါ...',
    'loc_acquiring': 'တည်နေရာရှာနေ...', 'loc_no_destination': 'ဦးတည်ရာသတ်မှတ်ပါ',
    'dir_north': 'မြောက်', 'dir_northeast': 'အရှေ့မြောက်', 'dir_east': 'အရှေ့', 'dir_southeast': 'အရှေ့တောင်',
    'dir_south': 'တောင်', 'dir_southwest': 'အနောက်တောင်', 'dir_west': 'အနောက်', 'dir_northwest': 'အနောက်မြောက်',
    'nav_straight': 'ဖြောင့်', 'nav_turn_right': 'ညာ', 'nav_turn_left': 'ဘယ်',
    'nav_u_turn': 'U-turn', 'nav_arrived_panel': 'ရောက်ပြီ!',
    'danger_dismiss': 'ပိတ်', 'overlay_flood': 'ရေကြီး', 'overlay_power': 'လျှပ်စစ်',
    'dr_badge': 'GPS ပျောက် — ခန့်မှန်းတည်နေရာ (@steps ခြေလှမ်း)',
    'splash_agree': 'သဘောတူ', 'report_passable': 'ဖြတ်သွားနိုင်', 'report_blocked': 'ပိတ်ဆို့',
    'gps_none': 'GPS မရှိ', 'ble_off': 'BLE ပိတ်', 'power_saving': 'ဓာတ်အားချွေတာ',
    'tts_dir_right': 'ညာ', 'tts_dir_left': 'ဘယ်', 'tts_arrived': 'ဦးတည်ရာသို့ ရောက်ပြီ။',
    'profile_save': 'သိမ်းဆည်း', 'triage_back': 'နောက်', 'btn_clear': 'ဖျက်',
    'nav_calculating': 'တွက်ချက်နေ...', 'nav_safe_confirm': 'အတည်ပြု',
    'splash_ready': 'အဆင်သင့်', 'offline_banner': 'Offline မုဒ်',
    'map_download_retry': 'ထပ်ကြိုး', 'map_download_done': 'ပြီး',
    'msg_no_data': 'ဒေတာမရှိ', 'verified': 'အတည်ပြုပြီ',
})

LANGS['si'] = make_simple_lang('si', 'සිංහල', '🇱🇰', {
    'tab_map': 'සිතියම', 'tab_guide': 'මාර්ගෝපදේශ', 'tab_settings': 'සැකසීම්',
    'status_safe': '✅ ආරක්ෂිත', 'status_danger': '⚠️ අවදානම',
    'btn_yes_arrived': 'ඔව්, ළඟා විය', 'btn_cancel': 'අවලංගු',
    'bot_analyzing': 'විශ්ලේෂණය...', 'header_ai_guide': 'AI ආරක්ෂණ මාර්ගෝපදේශ',
    'btn_arrived_label': 'රැකවරණ ස්ථානයට ළඟා විය', 'waiting_destination': 'ගමනාන්තය සකසන්න...',
    'loc_acquiring': 'ස්ථානය ලබාගනිමින්...', 'loc_no_destination': 'ගමනාන්තය සකසන්න',
    'dir_north': 'උ', 'dir_northeast': 'ඊශ', 'dir_east': 'නැ', 'dir_southeast': 'ඊ',
    'dir_south': 'ද', 'dir_southwest': 'නිරිත', 'dir_west': 'බ', 'dir_northwest': 'වයඹ',
    'nav_straight': 'කෙළින්', 'nav_turn_right': 'දකුණ', 'nav_turn_left': 'වාම',
    'nav_u_turn': 'U-හැරවීම', 'nav_arrived_panel': 'ළඟා විය!',
    'danger_dismiss': 'වසන්න', 'overlay_flood': 'ගංවතුර', 'overlay_power': 'විදුලිය',
    'dr_badge': 'GPS නැත — ස්ථාන ඇස්තමේන්තුව (@steps පියවර)',
    'splash_agree': 'එකඟ', 'report_passable': 'ගත හැකිය', 'report_blocked': 'අවහිර',
    'gps_none': 'GPS නැත', 'ble_off': 'BLE නැත', 'power_saving': 'බලශක්ති ඉතිරිකිරීම',
    'tts_dir_right': 'දකුණ', 'tts_dir_left': 'වාම', 'tts_arrived': 'ගමනාන්තයට ළඟා විය.',
    'profile_save': 'සුරකින්න', 'triage_back': 'ආපසු', 'btn_clear': 'මකන්න',
    'nav_calculating': 'ගණනය කිරීම...', 'nav_safe_confirm': 'තහවුරු',
    'splash_ready': 'සූදානම්', 'offline_banner': 'Offline ප්‍රකාරය',
    'map_download_retry': 'නැවත උත්සාහ', 'map_download_done': 'සම්පූර්ණ',
    'msg_no_data': 'දත්ත නැත', 'verified': 'තහවුරු',
})

LANGS['hi'] = make_simple_lang('hi', 'हिन्दी', '🇮🇳', {
    'tab_map': 'नक्शा', 'tab_guide': 'मार्गदर्शन', 'tab_settings': 'सेटिंग',
    'status_safe': '✅ सुरक्षित', 'status_danger': '⚠️ खतरा',
    'btn_yes_arrived': 'हाँ, पहुँच गया', 'btn_cancel': 'रद्द',
    'bot_analyzing': 'विश्लेषण...', 'header_ai_guide': 'AI निकासी मार्गदर्शन',
    'btn_arrived_label': 'आश्रय स्थल पहुँचा', 'waiting_destination': 'गंतव्य सेट करें...',
    'loc_acquiring': 'स्थान प्राप्त हो रहा है...', 'loc_no_destination': 'गंतव्य सेट करें',
    'dir_north': 'उ', 'dir_northeast': 'ईशान', 'dir_east': 'पू', 'dir_southeast': 'आग्नेय',
    'dir_south': 'द', 'dir_southwest': 'नैऋत्य', 'dir_west': 'प', 'dir_northwest': 'वायव्य',
    'nav_straight': 'सीधे', 'nav_turn_right': 'दाएँ', 'nav_turn_left': 'बाएँ',
    'nav_u_turn': 'U-टर्न', 'nav_arrived_panel': 'पहुँच गए!',
    'danger_dismiss': 'बंद करें', 'overlay_flood': 'बाढ़', 'overlay_power': 'बिजली',
    'dr_badge': 'GPS गायब — अनुमानित स्थान (@steps कदम)',
    'splash_agree': 'सहमत', 'report_passable': 'जाने योग्य', 'report_blocked': 'अवरुद्ध',
    'gps_none': 'GPS नहीं', 'ble_off': 'BLE बंद', 'power_saving': 'बैटरी बचत',
    'tts_dir_right': 'दाएँ', 'tts_dir_left': 'बाएँ', 'tts_arrived': 'आप गंतव्य पर पहुँच गए।',
    'profile_save': 'सहेजें', 'triage_back': 'वापस', 'btn_clear': 'साफ़',
    'nav_calculating': 'गणना...', 'nav_safe_confirm': 'पुष्टि',
    'splash_ready': 'तैयार', 'offline_banner': 'ऑफलाइन मोड',
    'map_download_retry': 'पुनः प्रयास', 'map_download_done': 'पूर्ण',
    'msg_no_data': 'डेटा नहीं', 'verified': 'सत्यापित',
})

LANGS['ne'] = make_simple_lang('ne', 'नेपाली', '🇳🇵', {
    'tab_map': 'नक्सा', 'tab_guide': 'मार्गदर्शन', 'tab_settings': 'सेटिङ',
    'status_safe': '✅ सुरक्षित', 'status_danger': '⚠️ खतरा',
    'btn_yes_arrived': 'हो, पुगियो', 'btn_cancel': 'रद्द',
    'bot_analyzing': 'विश्लेषण...', 'header_ai_guide': 'AI निकासी मार्गदर्शन',
    'btn_arrived_label': 'आश्रयस्थलमा पुगियो', 'waiting_destination': 'गन्तव्य सेट गर्नुस्...',
    'loc_acquiring': 'स्थान प्राप्त गर्दै...', 'loc_no_destination': 'गन्तव्य सेट गर्नुस्',
    'dir_north': 'उ', 'dir_northeast': 'ई', 'dir_east': 'पू', 'dir_southeast': 'आ',
    'dir_south': 'द', 'dir_southwest': 'न', 'dir_west': 'प', 'dir_northwest': 'व',
    'nav_straight': 'सोझो', 'nav_turn_right': 'दायाँ', 'nav_turn_left': 'बायाँ',
    'nav_u_turn': 'U-टर्न', 'nav_arrived_panel': 'पुगियो!',
    'danger_dismiss': 'बन्द', 'overlay_flood': 'बाढी', 'overlay_power': 'बिजुली',
    'dr_badge': 'GPS हराएको — अनुमानित स्थान (@steps पाइला)',
    'splash_agree': 'सहमत', 'report_passable': 'जान सकिन्छ', 'report_blocked': 'अवरुद्ध',
    'gps_none': 'GPS छैन', 'ble_off': 'BLE बन्द', 'power_saving': 'ब्याट्री बचत',
    'tts_dir_right': 'दायाँ', 'tts_dir_left': 'बायाँ', 'tts_arrived': 'गन्तव्यमा पुग्नुभयो।',
    'profile_save': 'बचत', 'triage_back': 'फिर्ता', 'btn_clear': 'खाली',
    'nav_calculating': 'गणना...', 'nav_safe_confirm': 'पुष्टि',
    'splash_ready': 'तयार', 'offline_banner': 'अफलाइन मोड',
    'map_download_retry': 'पुनः प्रयास', 'map_download_done': 'सम्पन्न',
    'msg_no_data': 'डाटा छैन', 'verified': 'प्रमाणित',
})

LANGS['bn'] = make_simple_lang('bn', 'বাংলা', '🇧🇩', {
    'tab_map': 'মানচিত্র', 'tab_guide': 'গাইড', 'tab_settings': 'সেটিংস',
    'status_safe': '✅ নিরাপদ', 'status_danger': '⚠️ বিপদ',
    'btn_yes_arrived': 'হ্যাঁ, পৌঁছেছি', 'btn_cancel': 'বাতিল',
    'bot_analyzing': 'বিশ্লেষণ...', 'header_ai_guide': 'AI উচ্ছেদ গাইড',
    'btn_arrived_label': 'আশ্রয়স্থলে পৌঁছেছি', 'waiting_destination': 'গন্তব্য সেট করুন...',
    'loc_acquiring': 'অবস্থান পাচ্ছি...', 'loc_no_destination': 'গন্তব্য সেট করুন',
    'dir_north': 'উ', 'dir_northeast': 'উপূ', 'dir_east': 'পূ', 'dir_southeast': 'দপূ',
    'dir_south': 'দ', 'dir_southwest': 'দপ', 'dir_west': 'প', 'dir_northwest': 'উপ',
    'nav_straight': 'সোজা', 'nav_turn_right': 'ডানে', 'nav_turn_left': 'বামে',
    'nav_u_turn': 'U-টার্ন', 'nav_arrived_panel': 'পৌঁছেছি!',
    'danger_dismiss': 'বন্ধ', 'overlay_flood': 'বন্যা', 'overlay_power': 'বিদ্যুৎ',
    'dr_badge': 'GPS হারিয়েছে — আনুমানিক অবস্থান (@steps পদক্ষেপ)',
    'splash_agree': 'সম্মত', 'report_passable': 'যাওয়া যাবে', 'report_blocked': 'বন্ধ',
    'gps_none': 'GPS নেই', 'ble_off': 'BLE বন্ধ', 'power_saving': 'ব্যাটারি সাশ্রয়',
    'tts_dir_right': 'ডানে', 'tts_dir_left': 'বামে', 'tts_arrived': 'গন্তব্যে পৌঁছেছেন।',
    'profile_save': 'সংরক্ষণ', 'triage_back': 'ফিরে', 'btn_clear': 'মুছুন',
    'nav_calculating': 'গণনা...', 'nav_safe_confirm': 'নিশ্চিত',
    'splash_ready': 'প্রস্তুত', 'offline_banner': 'অফলাইন মোড',
    'map_download_retry': 'পুনরায় চেষ্টা', 'map_download_done': 'সম্পন্ন',
    'msg_no_data': 'কোনো ডেটা নেই', 'verified': 'যাচাইকৃত',
})

LANGS['es'] = make_simple_lang('es', 'Español', '🇪🇸', {
    'tab_map': 'Mapa', 'tab_guide': 'Guía', 'tab_settings': 'Ajustes',
    'status_safe': '✅ SEGURO', 'status_danger': '⚠️ PELIGRO',
    'btn_yes_arrived': 'Sí, llegué', 'btn_cancel': 'Cancelar',
    'bot_analyzing': 'Analizando...', 'header_ai_guide': 'Guía de Evacuación AI',
    'btn_arrived_label': 'Llegué al Refugio', 'waiting_destination': 'Establecer destino...',
    'loc_acquiring': 'Obteniendo ubicación...', 'loc_no_destination': 'Establece un destino',
    'dir_north': 'N', 'dir_northeast': 'NE', 'dir_east': 'E', 'dir_southeast': 'SE',
    'dir_south': 'S', 'dir_southwest': 'SO', 'dir_west': 'O', 'dir_northwest': 'NO',
    'nav_straight': 'Recto', 'nav_turn_right': 'Girar a la derecha', 'nav_turn_left': 'Girar a la izquierda',
    'nav_u_turn': 'Dar la vuelta', 'nav_arrived_panel': '¡Llegué!',
    'danger_dismiss': 'Cerrar', 'overlay_flood': 'Inundación', 'overlay_power': 'Electricidad',
    'dr_badge': 'GPS perdido — Posición estimada (@steps pasos)',
    'splash_agree': 'Acepto', 'report_passable': 'Transitable', 'report_blocked': 'Bloqueado',
    'gps_none': 'Sin GPS', 'ble_off': 'BLE apagado', 'power_saving': 'Ahorro de energía',
    'tts_dir_right': 'derecha', 'tts_dir_left': 'izquierda', 'tts_arrived': 'Ha llegado a su destino.',
    'profile_save': 'Guardar', 'triage_back': 'Volver', 'btn_clear': 'Borrar',
    'nav_calculating': 'Calculando...', 'nav_safe_confirm': 'Confirmar',
    'splash_ready': 'Listo', 'offline_banner': 'Modo sin conexión',
    'map_download_retry': 'Reintentar', 'map_download_done': 'Completado',
    'msg_no_data': 'Sin datos', 'verified': 'Verificado',
})

LANGS['pt'] = make_simple_lang('pt', 'Português', '🇧🇷', {
    'tab_map': 'Mapa', 'tab_guide': 'Guia', 'tab_settings': 'Configurações',
    'status_safe': '✅ SEGURO', 'status_danger': '⚠️ PERIGO',
    'btn_yes_arrived': 'Sim, Cheguei', 'btn_cancel': 'Cancelar',
    'bot_analyzing': 'Analisando...', 'header_ai_guide': 'Guia de Evacuação AI',
    'btn_arrived_label': 'Cheguei ao Abrigo', 'waiting_destination': 'Definir destino...',
    'loc_acquiring': 'Obtendo localização...', 'loc_no_destination': 'Defina um destino',
    'dir_north': 'N', 'dir_northeast': 'NE', 'dir_east': 'L', 'dir_southeast': 'SE',
    'dir_south': 'S', 'dir_southwest': 'SO', 'dir_west': 'O', 'dir_northwest': 'NO',
    'nav_straight': 'Em frente', 'nav_turn_right': 'Virar à direita', 'nav_turn_left': 'Virar à esquerda',
    'nav_u_turn': 'Retorno', 'nav_arrived_panel': 'Chegou!',
    'danger_dismiss': 'Fechar', 'overlay_flood': 'Inundação', 'overlay_power': 'Eletricidade',
    'dr_badge': 'GPS perdido — Posição estimada (@steps passos)',
    'splash_agree': 'Concordo', 'report_passable': 'Transitável', 'report_blocked': 'Bloqueado',
    'gps_none': 'Sem GPS', 'ble_off': 'BLE desligado', 'power_saving': 'Economia de energia',
    'tts_dir_right': 'direita', 'tts_dir_left': 'esquerda', 'tts_arrived': 'Você chegou ao destino.',
    'profile_save': 'Salvar', 'triage_back': 'Voltar', 'btn_clear': 'Limpar',
    'nav_calculating': 'Calculando...', 'nav_safe_confirm': 'Confirmar',
    'splash_ready': 'Pronto', 'offline_banner': 'Modo offline',
    'map_download_retry': 'Tentar novamente', 'map_download_done': 'Concluído',
    'msg_no_data': 'Sem dados', 'verified': 'Verificado',
})

LANGS['mn'] = make_simple_lang('mn', 'Монгол', '🇲🇳', {
    'tab_map': 'Газрын зураг', 'tab_guide': 'Удирдамж', 'tab_settings': 'Тохиргоо',
    'status_safe': '✅ АЮУЛГҮЙ', 'status_danger': '⚠️ АЮУЛ',
    'btn_yes_arrived': 'Тийм, Хүрлээ', 'btn_cancel': 'Цуцлах',
    'bot_analyzing': 'Шинжилж байна...', 'header_ai_guide': 'AI Нүүлгэн шилжүүлэлтийн удирдамж',
    'btn_arrived_label': 'Хамгаалалтын газарт хүрлээ', 'waiting_destination': 'Очих газраа тохируул...',
    'loc_acquiring': 'Байршил авч байна...', 'loc_no_destination': 'Очих газраа тохируул',
    'dir_north': 'Х', 'dir_northeast': 'ХЗ', 'dir_east': 'З', 'dir_southeast': 'ӨЗ',
    'dir_south': 'Ө', 'dir_southwest': 'ӨБ', 'dir_west': 'Б', 'dir_northwest': 'ХБ',
    'nav_straight': 'Шулуун', 'nav_turn_right': 'Баруун эргэ', 'nav_turn_left': 'Зүүн эргэ',
    'nav_u_turn': 'U-эргэлт', 'nav_arrived_panel': 'Хүрлээ!',
    'danger_dismiss': 'Хаах', 'overlay_flood': 'Үер', 'overlay_power': 'Цахилгаан',
    'dr_badge': 'GPS алдагдсан — Тооцоолсон байршил (@steps алхам)',
    'splash_agree': 'Зөвшөөрөх', 'report_passable': 'Гарч болно', 'report_blocked': 'Хаагдсан',
    'gps_none': 'GPS байхгүй', 'ble_off': 'BLE унтарсан', 'power_saving': 'Батарей хэмнэлт',
    'tts_dir_right': 'баруун', 'tts_dir_left': 'зүүн', 'tts_arrived': 'Та очих газартаа хүрлээ.',
    'profile_save': 'Хадгалах', 'triage_back': 'Буцах', 'btn_clear': 'Цэвэрлэх',
    'nav_calculating': 'Тооцоолж байна...', 'nav_safe_confirm': 'Баталгаажуулах',
    'splash_ready': 'Бэлэн', 'offline_banner': 'Офлайн горим',
    'map_download_retry': 'Дахин оролдох', 'map_download_done': 'Дуусгасан',
    'msg_no_data': 'Өгөгдөл байхгүй', 'verified': 'Баталгаажсан',
})

LANGS['uz'] = make_simple_lang('uz', "O'zbek", '🇺🇿', {
    'tab_map': 'Xarita', 'tab_guide': 'Qoʻllanma', 'tab_settings': 'Sozlamalar',
    'status_safe': '✅ XAVFSIZ', 'status_danger': '⚠️ XAVF',
    'btn_yes_arrived': 'Ha, Yetib keldim', 'btn_cancel': 'Bekor qilish',
    'bot_analyzing': 'Tahlil qilinmoqda...', 'header_ai_guide': 'AI Evakuatsiya qoʻllanmasi',
    'btn_arrived_label': 'Boshpanaga yetib keldim', 'waiting_destination': 'Manzilni belgilang...',
    'loc_acquiring': 'Joylashuv olinmoqda...', 'loc_no_destination': 'Manzilni belgilang',
    'dir_north': 'Sh', 'dir_northeast': 'ShS', 'dir_east': 'S', 'dir_southeast': 'JS',
    'dir_south': 'J', 'dir_southwest': 'JG', 'dir_west': 'G', 'dir_northwest': 'ShG',
    'nav_straight': 'Toʻgʻri', 'nav_turn_right': 'Oʻngga bur', 'nav_turn_left': 'Chapga bur',
    'nav_u_turn': 'Orqaga qayt', 'nav_arrived_panel': 'Yetib keldim!',
    'danger_dismiss': 'Yopish', 'overlay_flood': 'Sel', 'overlay_power': 'Elektr',
    'dr_badge': "GPS yoʻqoldi — Taxminiy joylashuv (@steps qadam)",
    'splash_agree': 'Roziman', 'report_passable': 'Oʻtish mumkin', 'report_blocked': 'Toʻsilgan',
    'gps_none': 'GPS yoʻq', 'ble_off': 'BLE oʻchiq', 'power_saving': 'Quvvat tejash',
    'tts_dir_right': 'oʻngga', 'tts_dir_left': 'chapga', 'tts_arrived': 'Manzilga yetib keldingiz.',
    'profile_save': 'Saqlash', 'triage_back': 'Orqaga', 'btn_clear': 'Tozalash',
    'nav_calculating': 'Hisoblanmoqda...', 'nav_safe_confirm': 'Tasdiqlash',
    'splash_ready': 'Tayyor', 'offline_banner': 'Oflayn rejim',
    'map_download_retry': 'Qayta urinish', 'map_download_done': 'Tugallandi',
    'msg_no_data': 'Maʼlumot yoʻq', 'verified': 'Tasdiqlangan',
})


def escape_dart(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n')

def lang_to_dart(code, d):
    lines = [f"    '{code}': {{"]
    for k, v in d.items():
        if k in ('name', 'flag'):
            continue
        lines.append(f"      '{escape_dart(k)}': '{escape_dart(v)}',")
    lines.append("    },")
    return '\n'.join(lines)

output = []
for code, d in LANGS.items():
    output.append(lang_to_dart(code, d))

print('\n'.join(output))
