
import 'package:flutter/material.dart';
import '../survival_data.dart'; // Import the base classes

class SurvivalDataJP {
  // --- Official Survival Guide (Strict 6 Items - JAPAN) ---
  static const List<SurvivalGuideItem> officialGuides = [
    SurvivalGuideItem(
      id: 'economy',
      icon: Icons.airline_seat_legroom_extra,
      title: {
        'en': 'Economy Class Syn.',
        'ja': 'エコノミークラス症候群',
        'th': 'โรคชั้นประหยัด',
        'zh': '经济舱综合征',
        'zh_TW': '經濟艙綜合症',
        'ko': '이코노미 클래스 증후군',
        'vi': 'Hội chứng ghế hạng phổ thông',
        'tl': 'Economy Class Syndrome',
        'ne': 'इकोनमी क्लास सिन्ड्रोम',
        'pt': 'Síndrome da Classe Econômica',
        'id': 'Sindrom Kelas Ekonomi',
        'my': 'စီးပွားရေးတန်း ဆင်ဒ်ရောမ်',
        'si': 'ආර්ථිකය පන්තිය සින්ඩ්‍රෝමය',
        'hi': 'इकोनॉमी क्लास सिंड्रोम',
        'es': 'Síndrome de Clase Turista',
        'mn': 'Эдийн засгийн ангиллын хам шинж',
        'uz': 'Iqtisodiy sinf sindromi',
        'bn': 'ইকোনমি ক্লাস সিন্ড্রোম',
      },
      action: {
        'en': 'Do ankle exercises. Drink water frequently.',
        'ja': '足首を回す運動をしましょう。水分をこまめに摂り、同じ姿勢で寝ないよう注意してください。',
        'th': 'ขยับข้อเท้าบ่อยๆ ดื่มน้ำสะอาดให้เพียงพอ',
        'zh': '经常活动脚踝，多喝水，避免长时间保持同一姿势。',
        'zh_TW': '經常活動腳踝，多喝水，避免長時間保持同一姿勢。',
        'ko': '발목을 자주 움직이세요. 물을 충분히 마시고 같은 자세를 오래 유지하지 마세요.',
        'vi': 'Thường xuyên vận động cổ chân. Uống đủ nước. Tránh giữ nguyên tư thế lâu.',
        'tl': 'Ilipat ang mga bukung-bukong nang madalas. Uminom ng tubig. Huwag manatili sa iisang posisyon.',
        'ne': 'खुट्टाको गोलिगाँठो घुमाउनुहोस्। पानी पिउनुहोस्। एउटै स्थितिमा नबस्नुहोस्।',
        'pt': 'Movimente os tornozelos frequentemente. Beba água. Não fique na mesma posição por muito tempo.',
        'id': 'Gerakkan pergelangan kaki secara teratur. Minum air yang cukup. Jangan diam dalam posisi yang sama terlalu lama.',
        'my': 'ကြာကြာ ခြေကုတ်ကို လှုပ်ရှားပါ။ ရေသောက်ပါ။ တူညီသောရပ်တည်မှုတွင် ကြာကြာမနေပါနှင့်။',
        'si': 'නිතරම කකුල් නද්ද චලනය කරන්න. ජලය පානය කරන්න. එකම ස්ථානයේ දීර්ඝ කාලයක් නොසිටින්න.',
        'hi': 'टखने नियमित रूप से घुमाएं। पानी पिएं। एक ही मुद्रा में लंबे समय तक न रहें।',
        'es': 'Mueva los tobillos frecuentemente. Beba agua. No permanezca en la misma posición por mucho tiempo.',
        'mn': 'Гагнуурыг байнга хөдөлгөж, ус уу. Нэг байрлалаар удаан суухаас зайлсхий.',
        'uz': "Tizzalarni muntazam harakatlantiring. Suv iching. Bir holatda uzoq o'tirmang.",
        'bn': 'গোড়ালি নিয়মিত ঘোরান। পানি পান করুন। একই অবস্থানে দীর্ঘক্ষণ থাকবেন না।',
      },
      source: 'MHLW / JSIM',
      steps: [
        SurvivalStep(instruction: {'en': 'Rotate ankles.', 'ja': '足首を回す', 'th': 'หมุนข้อเท้าซ้ายขวา'}, icon: Icons.refresh),
        SurvivalStep(instruction: {'en': 'Drink water.', 'ja': '水を飲む', 'th': 'ดื่มน้ำสะอาด'}, icon: Icons.local_drink),
        SurvivalStep(instruction: {'en': 'Walk around.', 'ja': '歩く', 'th': 'ลุกเดินยืดเส้นสาย'}, icon: Icons.directions_walk),
      ],
    ),
    SurvivalGuideItem(
      id: 'infection',
      icon: Icons.sanitizer,
      title: {
        'en': 'Infection Control',
        'ja': '感染症対策',
        'th': 'การป้องกันการติดเชื้อ',
        'zh': '感染预防',
        'zh_TW': '感染預防',
        'ko': '감염 예방',
        'vi': 'Kiểm soát nhiễm trùng',
        'tl': 'Kontrol sa Impeksyon',
        'ne': 'संक्रमण नियन्त्रण',
        'pt': 'Controle de Infecção',
        'id': 'Pengendalian Infeksi',
        'my': 'ကူးစက်ရောဂါ ထိန်းချုပ်ရေး',
        'si': 'ආසාදන පාලනය',
        'hi': 'संक्रमण नियंत्रण',
        'es': 'Control de Infecciones',
        'mn': 'Халдвар хяналт',
        'uz': 'Infeksiyani nazorat qilish',
        'bn': 'সংক্রমণ নিয়ন্ত্রণ',
      },
      action: {
        'en': 'Wash hands thoroughly. Wear masks. Ventilate.',
        'ja': '手洗い・うがいを徹底してください。マスクを着用し、定期的に換気を行いましょう。',
        'th': 'ล้างมือให้สะอาด สวมหน้ากากอนามัย และระบายอากาศอย่างสม่ำเสมอ',
        'zh': '彻底洗手，戴口罩，定期通风。',
        'zh_TW': '徹底洗手，戴口罩，定期通風。',
        'ko': '손을 철저히 씻고 마스크를 착용하고 환기하세요.',
        'vi': 'Rửa tay kỹ lưỡng. Đeo khẩu trang. Thông gió thường xuyên.',
        'tl': 'Maghugas ng kamay nang maigi. Magsuot ng maskara. Mag-ventilate.',
        'ne': 'राम्रोसँग हात धुनुहोस्। मास्क लगाउनुहोस्। नियमित हावा आउन दिनुहोस्।',
        'pt': 'Lave as mãos completamente. Use máscaras. Ventile regularmente.',
        'id': 'Cuci tangan secara menyeluruh. Pakai masker. Ventilasi teratur.',
        'my': 'လက်များကို သေချာဆေးကြောပါ။ မျက်နှာဖုံးတပ်ပါ။ လေဝင်လေထွက်ကောင်းအောင်ပြုပါ။',
        'si': 'අතේ හොඳින් සෝදන්න. මාස්කුව පළඳින්න. නිතිපතා වාතාශ්‍රය ලබා දෙන්න.',
        'hi': 'हाथ अच्छी तरह धोएं। मास्क पहनें। नियमित रूप से हवादार करें।',
        'es': 'Lávese las manos minuciosamente. Use mascarilla. Ventile regularmente.',
        'mn': 'Гарыг нарийн угааж, маск зүүж, тогтмол агааржуулна уу.',
        'uz': "Qo'llarni yaxshilab yuvib, niqob kiyib, muntazam shamollatib turing.",
        'bn': 'হাত ভালোভাবে ধুন। মাস্ক পরুন। নিয়মিত বায়ু চলাচল নিশ্চিত করুন।',
      },
      source: 'MHLW / CDC',
    ),
    SurvivalGuideItem(
      id: 'poisoning',
      icon: Icons.food_bank,
      title: {
        'en': 'Food Poisoning',
        'ja': '食中毒予防',
        'th': 'ความปลอดภัยทางอาหาร',
        'zh': '食品安全',
        'zh_TW': '食品安全',
        'ko': '식중독 예방',
        'vi': 'An toàn thực phẩm',
        'tl': 'Kaligtasan ng Pagkain',
        'ne': 'खाद्य सुरक्षा',
        'pt': 'Segurança Alimentar',
        'id': 'Keamanan Pangan',
        'my': 'အစားအသောက် ဘေးကင်းရေး',
        'si': 'ආහාර ආරක්ෂාව',
        'hi': 'खाद्य सुरक्षा',
        'es': 'Seguridad Alimentaria',
        'mn': 'Хоол хүнсний аюулгүй байдал',
        'uz': 'Oziq-ovqat xavfsizligi',
        'bn': 'খাদ্য নিরাপত্তা',
      },
      action: {
        'en': 'Eat distributed food immediately. No leftovers.',
        'ja': '配給された食事はすぐに食べてください。室温で放置しないでください。',
        'th': 'รับประทานอาหารที่แจกจ่ายทันที อย่าทิ้งอาหารไว้ที่อุณหภูมิห้อง',
        'zh': '配给的食物请立即食用。不要在室温下放置。',
        'zh_TW': '配給的食物請立即食用。不要在室溫下放置。',
        'ko': '배급된 음식은 바로 드세요. 실온에 방치하지 마세요.',
        'vi': 'Ăn ngay thức ăn được phân phát. Không để ở nhiệt độ phòng.',
        'tl': 'Kainin agad ang ipinamamahaging pagkain. Huwag iwan sa temperatura ng silid.',
        'ne': 'वितरित खाना तुरुन्त खानुहोस्। कोठाको तापमानमा नछोड्नुहोस्।',
        'pt': 'Coma os alimentos distribuídos imediatamente. Não deixe em temperatura ambiente.',
        'id': 'Makan makanan yang dibagikan segera. Jangan biarkan di suhu kamar.',
        'my': 'ဝေငှသောအစားအသောက်ကို ချက်ချင်းစားပါ။ အခန်းအပူချိန်တွင် မထားပါနှင့်။',
        'si': 'බෙදා දෙන ආහාර වහාම අනුභව කරන්න. කාමර උෂ්ණත්වයේ තබා නොගන්න.',
        'hi': 'वितरित भोजन तुरंत खाएं। कमरे के तापमान पर न छोड़ें।',
        'es': 'Coma los alimentos distribuidos inmediatamente. No los deje a temperatura ambiente.',
        'mn': 'Хуваарилсан хоолыг шууд идэж, өрөөний температурт орхихгүй байгаарай.',
        'uz': "Taqsimlangan ovqatni darhol yeng. Xona haroratida qoldirmang.",
        'bn': 'বিতরণ করা খাবার তাৎক্ষণিকভাবে খান। ঘরের তাপমাত্রায় রেখে দেবেন না।',
      },
      source: 'MHLW',
    ),
    SurvivalGuideItem(
      id: 'insulation',
      icon: Icons.thermostat,
      title: {
        'en': 'Cold Protection',
        'ja': '寒さ対策',
        'th': 'การป้องกันความหนาว',
        'zh': '防寒保暖',
        'zh_TW': '防寒保暖',
        'ko': '방한 대책',
        'vi': 'Bảo vệ chống lạnh',
        'tl': 'Proteksyon sa Lamig',
        'ne': 'चिसो/गर्मी संरक्षण',
        'pt': 'Proteção contra o Frio',
        'id': 'Perlindungan Dingin',
        'my': 'အအေး/အပူ ကာကွယ်ရေး',
        'si': 'සීතල/උෂ්ණ ආරක්ෂාව',
        'hi': 'ठंड/गर्मी सुरक्षा',
        'es': 'Protección contra el Frío/Calor',
        'mn': 'Хүйтэн/Халуунаас хамгаалалт',
        'uz': 'Sovuq/Issiqdan himoya',
        'bn': 'ঠান্ডা/গরম সুরক্ষা',
      },
      action: {
        'en': 'Layer clothes. Use cardboard for insulation.',
        'ja': '寒さには重ね着や段ボールを活用。',
        'th': 'สวมเสื้อผ้าหลายชั้นเมื่อหนาว ใช้กล่องกระดาษรองนอน',
        'zh': '多穿衣物，用纸板隔热。保持身体温暖。',
        'zh_TW': '多穿衣物，用紙板隔熱。保持身體溫暖。',
        'ko': '옷을 여러 겹 입고 골판지를 활용하세요. 몸을 따뜻하게 유지하세요.',
        'vi': 'Mặc nhiều lớp quần áo. Dùng bìa carton cách nhiệt. Giữ ấm cơ thể.',
        'tl': 'Magsuot ng maraming damit. Gumamit ng karton para sa insulation. Panatilihing mainit ang katawan.',
        'ne': 'धेरै कपडा लगाउनुहोस्। ताप्नका लागि कार्डबोर्ड प्रयोग गर्नुहोस्।',
        'pt': 'Vista roupas em camadas. Use papelão para isolamento. Mantenha o corpo aquecido.',
        'id': 'Kenakan banyak pakaian. Gunakan kardus untuk insulasi. Jaga tubuh tetap hangat.',
        'my': 'အဝတ်များစွာဝတ်ဆင်ပါ။ နွေးထွေးမှုအတွက် ကတ်ထူကိုအသုံးပြုပါ။',
        'si': 'ඇඳුම් ගොඩාක් ඇඳගන්න. ඉන්සුලේෂන් සඳහා කාඩ්බෝඩ් භාවිතා කරන්න.',
        'hi': 'कई परतों में कपड़े पहनें। इन्सुलेशन के लिए कार्डबोर्ड का उपयोग करें।',
        'es': 'Use ropa en capas. Use cartón para aislar. Mantenga el cuerpo caliente.',
        'mn': 'Давхарлаж хувцас өмс. Тусгаарлалтад зориулж картон ашигла.',
        'uz': "Ko'p qatlam kiyim kiy. Izolyatsiya uchun karton ishlat. Tanani iliq saqlang.",
        'bn': 'স্তরে স্তরে পোশাক পরুন। তাপ নিরোধের জন্য কার্ডবোর্ড ব্যবহার করুন।',
      },
      source: 'FDMA',
    ),
    SurvivalGuideItem(
      id: 'crime',
      icon: Icons.security,
      title: {
        'en': 'Crime Prevention',
        'ja': '防犯対策',
        'th': 'การป้องกันอาชญากรรม',
        'zh': '防犯对策',
        'zh_TW': '防犯對策',
        'ko': '방범 대책',
        'vi': 'Phòng chống tội phạm',
        'tl': 'Pag-iwas sa Krimen',
        'ne': 'अपराध रोकथाम',
        'pt': 'Prevenção ao Crime',
        'id': 'Pencegahan Kejahatan',
        'my': 'ရာဇဝတ်မှု ကာကွယ်ရေး',
        'si': 'අපරාධ වැළැක්වීම',
        'hi': 'अपराध रोकथाम',
        'es': 'Prevención del Crimen',
        'mn': 'Гэмт хэргээс урьдчилан сэргийлэх',
        'uz': 'Jinoyatning oldini olish',
        'bn': 'অপরাধ প্রতিরোধ',
      },
      action: {
        'en': 'Move in groups. Use buzzers.',
        'ja': '単独行動を避け、防犯ブザーを携帯。',
        'th': 'ไปเป็นกลุ่ม พกนกหวีด และดูแลของมีค่าตลอดเวลา',
        'zh': '避免单独行动，携带防身报警器。',
        'zh_TW': '避免單獨行動，攜帶防身報警器。',
        'ko': '혼자 행동하지 마세요. 방범 경보기를 지참하세요.',
        'vi': 'Tránh đi một mình. Mang theo còi báo động. Bảo vệ tài sản có giá trị.',
        'tl': 'Iwasang mag-isa. Magdala ng buzzer. Bantayan ang mahahalagang bagay.',
        'ne': 'एक्लो नजानुहोस्। अलार्म बजर बोक्नुहोस्। मूल्यवान वस्तु राम्रोसँग राख्नुहोस्।',
        'pt': 'Evite andar sozinho. Carregue um alarme pessoal. Guarde objetos de valor.',
        'id': 'Hindari bepergian sendirian. Bawa alarm pribadi. Jaga barang berharga.',
        'my': 'တစ်ယောက်တည်းသွားရောက်ခြင်းကို ရှောင်ကြဉ်ပါ။ နိုးကောက်ဘဲလ်ကိုင်ပါ။',
        'si': 'තනිව යාම වළකින්න. ඇලාම් බසර් රැගෙන යන්න. වටිනා දේ ආරක්ෂා කරගන්න.',
        'hi': 'अकेले जाने से बचें। व्यक्तिगत अलार्म ले जाएं। मूल्यवान चीजें सुरक्षित रखें।',
        'es': 'Evite ir solo. Lleve una alarma personal. Guarde objetos de valor.',
        'mn': 'Дангаараа явахаас зайлсхий. Гар дохиолол авч яв. Үнэт эдийг хамгаал.',
        'uz': "Yolg'iz yurishdan saqlaning. Shaxsiy signalizatsiya olib yuring. Qimmatbaho narsalarni asrang.",
        'bn': 'একা চলাফেরা করা এড়িয়ে চলুন। ব্যক্তিগত অ্যালার্ম বহন করুন। মূল্যবান জিনিসপত্র রক্ষা করুন।',
      },
      source: 'NPA',
    ),
    SurvivalGuideItem(
      id: 'rhythm',
      icon: Icons.nightlight_round,
      title: {
        'en': 'Daily Rhythm',
        'ja': '生活リズム',
        'th': 'จังหวะชีวิต',
        'zh': '日常节奏',
        'zh_TW': '日常節奏',
        'ko': '생활 리듬',
        'vi': 'Nhịp sinh hoạt',
        'tl': 'Pang-araw-araw na Gawain',
        'ne': 'दैनिक दिनचर्या',
        'pt': 'Rotina Diária',
        'id': 'Rutinitas Harian',
        'my': 'နေ့စဉ် နေထိုင်မှု စနစ်',
        'si': 'දිනපතා රිද්මය',
        'hi': 'दैनिक दिनचर्या',
        'es': 'Rutina Diaria',
        'mn': 'Өдөр тутмын дэглэм',
        'uz': 'Kunlik tartib',
        'bn': 'দৈনন্দিন রুটিন',
      },
      action: {
        'en': 'Separate sleep/wake areas. Keep regular hours.',
        'ja': '寝る場所と活動場所を分け、規則正しい生活を。',
        'th': 'แยกพื้นที่นอนและกิจกรรม พยายามรักษากิจวัตรประจำวัน',
        'zh': '将睡眠区与活动区分开，保持规律的生活节奏。',
        'zh_TW': '將睡眠區與活動區分開，保持規律的生活節奏。',
        'ko': '수면 공간과 활동 공간을 분리하고 규칙적인 생활을 유지하세요.',
        'vi': 'Tách biệt khu vực ngủ và hoạt động. Duy trì nhịp sinh hoạt đều đặn.',
        'tl': 'Ihiwalay ang lugar ng pagtulog at aktibidad. Panatilihing regular ang pamumuhay.',
        'ne': 'सुत्ने र गतिविधि क्षेत्र अलग गर्नुहोस्। नियमित दिनचर्या कायम राख्नुहोस्।',
        'pt': 'Separe as áreas de sono e atividade. Mantenha uma rotina regular.',
        'id': 'Pisahkan area tidur dan aktivitas. Pertahankan rutinitas yang teratur.',
        'my': 'အိပ်ရာဝင်နေရာနှင့် လုပ်ဆောင်ချိန်နေရာကို ခွဲခြားပါ။ ပုံမှန်နေထိုင်ပါ။',
        'si': 'නිද්‍රා ප්‍රදේශය සහ ක්‍රියාකාරකම් ප්‍රදේශය වෙන් කරන්න. නිතිපතා ජීවිතය පවත්වා ගන්න.',
        'hi': 'सोने और गतिविधि के क्षेत्र अलग करें। नियमित दिनचर्या बनाए रखें।',
        'es': 'Separe las áreas de sueño y actividad. Mantenga una rutina regular.',
        'mn': 'Унтах болон үйл ажиллагааны орон зайг тусгаарла. Тогтмол амьдралын хэв маягийг хадгал.',
        'uz': "Uyqu va faoliyat joylarini ajrating. Muntazam kundalik tartibni saqlab qoling.",
        'bn': 'ঘুমের এলাকা এবং কার্যকলাপের এলাকা আলাদা করুন। নিয়মিত দিনচর্যা বজায় রাখুন।',
      },
      source: 'Cabinet Office',
    ),
  ];

  // --- AI Support Items (Rest of the items) ---
  static const List<SurvivalGuideItem> aiSupportGuides = [
    SurvivalGuideItem(
      id: 'chronic',
      icon: Icons.medication,
      title: {
        'en': 'Chronic Illness / Medicine',
        'ja': '持病・薬について',
        'th': 'โรคเรื้อรัง/ยา',
        'zh': '慢性病/药物',
        'zh_TW': '慢性病/藥物',
        'ko': '지병/약',
        'vi': 'Bệnh mãn tính/thuốc',
        'tl': 'Malalang Sakit/Gamot',
        'ne': 'दीर्घकालीन रोग/औषधि',
        'pt': 'Doença Crônica/Medicação',
        'id': 'Penyakit Kronis/Obat',
        'my': 'နာတာရှည်ရောဂါ/ဆေး',
        'si': 'නිදන්ගත රෝගය/ඖෂධ',
        'hi': 'पुरानी बीमारी/दवाई',
        'es': 'Enfermedad Crónica/Medicación',
        'mn': 'Архаг өвчин/эм',
        'uz': 'Surunkali kasallik/dori',
        'bn': 'দীর্ঘস্থায়ী রোগ/ওষুধ',
      },
      action: {
        'en': 'Notify staff of your medicine tag (Okusuri Techo). Consult medical teams.',
        'ja': 'お薬手帳をスタッフに提示してください。巡回医師に持病を相談しましょう。',
        'th': 'แจ้งเจ้าหน้าที่เกี่ยวกับยาประจำตัว ปรึกษาทีมแพทย์',
      },
      source: 'JMA (Japan Medical Association)',
    ),
    SurvivalGuideItem(
      id: 'religion',
      icon: Icons.menu_book, 
      title: {
        'en': 'Religious Needs',
        'ja': '宗教的配慮',
        'th': 'ความต้องการทางศาสนา',
        'zh': '宗教需求',
        'zh_TW': '宗教需求',
        'ko': '종교적 배려',
        'vi': 'Nhu cầu tôn giáo',
        'tl': 'Relihiyosong Pangangailangan',
        'ne': 'धार्मिक आवश्यकता',
        'pt': 'Necessidades Religiosas',
        'id': 'Kebutuhan Agama',
        'my': 'ဘာသာရေး လိုအပ်ချက်',
        'si': 'ආගමික අවශ්‍යතා',
        'hi': 'धार्मिक जरूरतें',
        'es': 'Necesidades Religiosas',
        'mn': 'Шашны хэрэгцээ',
        'uz': 'Diniy ehtiyojlar',
        'bn': 'ধর্মীয় প্রয়োজনীয়তা',
      },
      action: {
        'en': 'Use "Help Card" for Halal/Prayer needs. Create a private space with partitions.',
        'ja': '「Help Card」でハラルや礼拝の必要性を伝えてください。パーティションで空間を確保します。',
        'th': 'ใช้ "Help Card" เพื่อแจ้งเรื่องอาหารฮาลาลหรือการละหมาด สร้างพื้นที่ส่วนตัวด้วยฉากกั้น',
      },
      source: 'Multicultural Coexistence Guidelines',
    ),
    SurvivalGuideItem(
      id: 'pet',
      icon: Icons.pets,
      title: {
        'en': 'Pet Evacuation',
        'ja': 'ペット同行避難',
        'th': 'สัตว์เลี้ยง',
        'zh': '宠物疏散',
        'zh_TW': '寵物疏散',
        'ko': '반려동물 피난',
        'vi': 'Sơ tán thú cưng',
        'tl': 'Paglikas ng Alagang Hayop',
        'ne': 'पाल्तु जनावर निकासी',
        'pt': 'Evacuação de Pets',
        'id': 'Evakuasi Hewan Peliharaan',
        'my': 'အိမ်မွေးတိရစ္ဆာန် ထွက်ပြေးရေး',
        'si': 'සුරතල් සතුන් ඉවත් කිරීම',
        'hi': 'पालतू जानवर निकासी',
        'es': 'Evacuación de Mascotas',
        'mn': 'Гэрийн тэжээвэр амьтан нүүлгэх',
        'uz': 'Uy hayvonlarini evakuatsiya qilish',
        'bn': 'পোষা প্রাণী সরিয়ে নেওয়া',
      },
      action: {
        'en': 'Keep pets in cages. designate a pet area. Manage waste properly.',
        'ja': 'ケージに入れ、専用エリアを利用してください。排泄物の処理を徹底しましょう。',
        'th': 'ขังสัตว์เลี้ยงในกรง ใช้พื้นที่สำหรับสัตว์เลี้ยง จัดการสิ่งขับถ่ายให้เรียบร้อย',
      },
      source: 'Ministry of the Environment',
    ),
    SurvivalGuideItem(
      id: 'mental',
      icon: Icons.psychology,
      title: {
        'en': 'Mental Care',
        'ja': '心のケア',
        'th': 'สุขภาพจิต',
        'zh': '心理支持',
        'zh_TW': '心理支援',
        'ko': '마음 돌봄',
        'vi': 'Chăm sóc tinh thần',
        'tl': 'Pag-aalaga ng Isip',
        'ne': 'मानसिक हेरचाह',
        'pt': 'Saúde Mental',
        'id': 'Kesehatan Mental',
        'my': 'စိတ်ကျန်းမာရေး ဂရုစိုက်ရေး',
        'si': 'මානසික සෞඛ්‍ය සේවා',
        'hi': 'मानसिक देखभाल',
        'es': 'Salud Mental',
        'mn': 'Сэтгэлийн эрүүл мэндийн тусламж',
        'uz': "Ruhiy salomatlik g'amxo'rligi",
        'bn': 'মানসিক স্বাস্থ্য সেবা',
      },
      action: {
        'en': 'Practice "Grounding" or Deep Breathing. It is okay to cry or be scared.',
        'ja': '深呼吸や「グラウンディング」を試して。泣いたり怖がるのは自然な反応です。',
        'th': 'ฝึกหายใจลึกๆ หรือ Grounding การร้องไห้หรือกลัวเป็นเรื่องปกติ',
      },
      source: 'WHO / MHLW',
      steps: [
        SurvivalStep(instruction: {'en': 'Breathe deeply.', 'ja': '深呼吸する', 'th': 'หายใจเข้าลึกๆ'}, icon: Icons.air),
        SurvivalStep(instruction: {'en': 'Talk to someone.', 'ja': '誰かと話す', 'th': 'คุยกับใครสักคน'}, icon: Icons.record_voice_over),
      ],
    ),
    SurvivalGuideItem(
      id: 'care',
      icon: Icons.accessible,
      title: {
        'en': 'Nursing Care',
        'ja': '介護・介助',
        'th': 'การดูแลผู้ป่วย',
        'zh': '护理辅助',
        'zh_TW': '護理輔助',
        'ko': '간호/개호',
        'vi': 'Điều dưỡng/hỗ trợ',
        'tl': 'Pag-aalaga/Tulong',
        'ne': 'हेरचाह/सहायता',
        'pt': 'Cuidados de Enfermagem',
        'id': 'Perawatan/Bantuan',
        'my': 'စောင့်ရှောက်မှု/ကူညီမှု',
        'si': 'හෙද සේවය/සහාය',
        'hi': 'नर्सिंग/सहायता',
        'es': 'Enfermería/Asistencia',
        'mn': 'Сувилах/туслах',
        'uz': 'Hamshiralik/yordam',
        'bn': 'নার্সিং/সহায়তা',
      },
      action: {
        'en': 'Ask for accessible toilets and support. Look for "Welfare Shelter" info.',
        'ja': '多目的トイレや介助を依頼してください。「福祉避難所」への移動も検討されます。',
        'th': 'ขอความช่วยเหลือเรื่องห้องน้ำและการดูแล มองหาข้อมูล "ศูนย์พักพิงสำหรับผู้ต้องการการดูแลพิเศษ"',
      },
      source: 'MHLW',
    ),
    SurvivalGuideItem(
      id: 'hygiene',
      icon: Icons.wash,
      title: {
        'en': 'Toilet & Hygiene',
        'ja': 'トイレ・衛生',
        'th': 'ห้องน้ำ/สุขอนามัย',
        'zh': '厕所/卫生',
        'zh_TW': '廁所/衛生',
        'ko': '화장실/위생',
        'vi': 'Nhà vệ sinh/vệ sinh',
        'tl': 'Palikuran/Kalinisan',
        'ne': 'शौचालय/सरसफाई',
        'pt': 'Banheiro/Higiene',
        'id': 'Toilet/Kebersihan',
        'my': 'အိမ်သာ/သန့်ရှင်းရေး',
        'si': 'වැසිකිළි/සනීප',
        'hi': 'शौचालय/स्वच्छता',
        'es': 'Baño/Higiene',
        'mn': 'Ариун цэврийн өрөө/эрүүл ахуй',
        'uz': 'Hojatxona/gigiena',
        'bn': 'টয়লেট/স্বাস্থ্যবিধি',
      },
      action: {
        'en': 'Use portable toilets if available. Keep hands clean. Segregate waste.',
        'ja': '簡易トイレを利用し、手指消毒を徹底。ゴミは分別して密封してください。',
        'th': 'ใช้ห้องน้ำแบบพกพาหากมี ล้างมือให้สะอาด แยกขยะ',
      },
      source: 'MHLW',
    ),
    SurvivalGuideItem(
      id: 'battery',
      icon: Icons.battery_saver,
      title: {
        'en': 'Battery Saving',
        'ja': 'スマホ・電源',
        'th': 'ประหยัดแบตเตอรี่',
        'zh': '手机/电源',
        'zh_TW': '手機/電源',
        'ko': '스마트폰/전원',
        'vi': 'Điện thoại/nguồn điện',
        'tl': 'Telepono/Kapangyarihan',
        'ne': 'मोबाइल/विद्युत',
        'pt': 'Celular/Energia',
        'id': 'HP/Sumber Daya',
        'my': 'မိုဘိုင်း/ဓာတ်အားရင်းမြစ်',
        'si': 'දුරකථනය/විදුලිය',
        'hi': 'मोबाइल/बिजली',
        'es': 'Móvil/Energía',
        'mn': 'Утас/цахилгаан',
        'uz': 'Telefon/elektr',
        'bn': 'মোবাইল/বিদ্যুৎ',
      },
      action: {
        'en': 'Turn on Low Power Mode. Lower brightness. Turn off Wi-Fi/Bluetooth if not used.',
        'ja': '低電力モードをオン、画面を暗く、Wi-Fi/Bluetoothはオフに。',
        'th': 'เปิดโหมดประหยัดพลังงาน ลดความสว่างหน้าจอ ปิด Wi-Fi/Bluetooth หากไม่ได้ใช้',
      },
      source: 'Internal Affairs & Communications',
    ),
    SurvivalGuideItem(
      id: 'female',
      icon: Icons.spa,
      title: {
        'en': "Women's Care",
        'ja': '女性のケア',
        'th': 'สำหรับผู้หญิง',
        'zh': '女性关怀',
        'zh_TW': '女性關懷',
        'ko': '여성 돌봄',
        'vi': 'Chăm sóc phụ nữ',
        'tl': 'Pag-aalaga ng Kababaihan',
        'ne': 'महिला हेरचाह',
        'pt': 'Cuidados com Mulheres',
        'id': 'Perawatan Wanita',
        'my': 'အမျိုးသမီး ဂရုစိုက်မှု',
        'si': 'කාන්තා සෞඛ්‍ය',
        'hi': 'महिला देखभाल',
        'es': 'Atención a la Mujer',
        'mn': 'Эмэгтэйчүүдийн халамж',
        'uz': "Ayollar g'amxo'rligi",
        'bn': 'মহিলাদের যত্ন',
      },
      action: {
        'en': 'Ask female staff for sanitary products. Ensure privacy in changing areas.',
        'ja': '生理用品は女性スタッフに相談を。着替えや授乳スペースのプライバシー確保を。',
        'th': 'ขอผ้าอนามัยจากเจ้าหน้าที่หญิง ตรวจสอบความเป็นส่วนตัวในพื้นที่เปลี่ยนเสื้อผ้า',
      },
      source: 'Gender Equality Bureau',
    ),
    SurvivalGuideItem(
      id: 'info',
      icon: Icons.radio,
      title: {
        'en': 'Information Gathering',
        'ja': '情報の集め方',
        'th': 'การหาข้อมูล',
        'zh': '信息收集',
        'zh_TW': '資訊收集',
        'ko': '정보 수집',
        'vi': 'Thu thập thông tin',
        'tl': 'Pagtitipon ng Impormasyon',
        'ne': 'जानकारी संकलन',
        'pt': 'Coleta de Informações',
        'id': 'Pengumpulan Informasi',
        'my': 'သတင်းအချက်အလက် စုဆောင်းခြင်း',
        'si': 'තොරතුරු එකතු කිරීම',
        'hi': 'जानकारी एकत्र करना',
        'es': 'Recopilación de Información',
        'mn': 'Мэдээлэл цуглуулах',
        'uz': "Ma'lumot yig'ish",
        'bn': 'তথ্য সংগ্রহ',
      },
      action: {
        'en': 'Trust official sources (Radio/Govt Apps). Avoid rumors.',
        'ja': 'ラジオや自治体アプリなど、公式情報を信頼してください。デマに注意。',
        'th': 'เชื่อถือแหล่งข้อมูลที่เป็นทางการ (วิทยุ/แอปของรัฐบาล) ระวังข่าวลือ',
      },
      source: 'Fire and Disaster Management Agency',
    ),
    SurvivalGuideItem(
      id: 'money',
      icon: Icons.attach_money,
      title: {
        'en': 'Cash & Valuables',
        'ja': 'お金・貴重品',
        'th': 'お金・貴重品',
        'zh': '现金/贵重物品',
        'zh_TW': '現金/貴重物品',
        'ko': '현금/귀중품',
        'vi': 'Tiền mặt/tài sản quý',
        'tl': 'Cash/Mahahalagang Bagay',
        'ne': 'नगद/मूल्यवान सामान',
        'pt': 'Dinheiro em Espécie/Objetos de Valor',
        'id': 'Uang Tunai/Benda Berharga',
        'my': 'ငွေသား/တန်ဖိုးရှိ ပစ္စည်းများ',
        'si': 'මුදල්/වටිනා දේ',
        'hi': 'नकद/कीमती सामान',
        'es': 'Dinero en Efectivo/Objetos de Valor',
        'mn': 'Бэлэн мөнгө/үнэт зүйл',
        'uz': 'Naqd pul/qimmatbaho buyumlar',
        'bn': 'নগদ/মূল্যবান জিনিসপত্র',
      },
      action: {
        'en': 'Keep cash and ID on you. Do not leave them in shared spaces.',
        'ja': '現金と身分証は肌身離さず携帯。共有スペースに放置しないでください。',
        'th': 'พกเงินสดและบัตรประจำตัวติดตัว อย่าทิ้งไว้ในพื้นที่ส่วนกลาง',
      },
      source: 'National Police Agency',
    ),
  ];
}
